name: Pre-commit Hook Validation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  validate-pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
      - name: Cache Renv dirs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/R/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
    
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
